### ISSUE TITLE
module 'utils.utils' has no attribute 'k_largest_index_argpartition'

### ISSUE THREAD

**Issue by qingchenkanlu** [skumra/romannet#2]
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 191, in agent
    self.policy()
  File "main.py", line 165, in policy
    self.compute_action(explore_actions, self.grasp_predictions)
  File "main.py", line 177, in compute_action
    maximas = utils.k_largest_index_argpartition(predictions, k=10)
AttributeError: module 'utils.utils' has no attribute 'k_largest_index_argpartition'

**Comment by qingchenkanlu** [comment]
- The repository only provide .dylib, which can not be used in Linux, can you provide .so?
- The pretrained model can also be provided?
